title: The Trail Busters
email: info@thetrailbusters.com
description: >- # this means to ignore newlines until "baseurl:"
  The Trail Busters podcast explores the realm of outdoor adventures.
  Three friends, Ethan, Bing and Will, share the good, the bad, and
  the goofy experiences of their outdoor adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thetrailbusters.com" # the base hostname & protocol for your site, e.g. http://example.com

#social
twitter_username: thetrailbusters
facebook_username: thetrailbusters
instagram_username: thetrailbusters

#feeds
apple_podcasts: https://podcasts.apple.com/ca/podcast/the-trail-busters/id1524819287
google_podcasts: https://podcasts.google.com/feed/aHR0cHM6Ly90aGV0cmFpbGJ1c3RlcnMuY29tL2VwaXNvZGVzLnhtbA
spotify_podcasts: https://open.spotify.com/show/7vkNVZ1XQHCIL65mwlKAiR
rss_feed: https://thetrailbusters.com/episodes.xml

# Podcast config
podcast_url: http://www.thetrailbusters.com
podcast_album_art: /img/trailbusters.jpg
podcast_title: The Trail Busters
podcast_owner: Ethan Aubuchon, Bing Lin, and Will Damon
podcast_email: contact@thetrailbusters.com
podcast_category: Sports
podcast_subcategory_one: Wilderness
podcast_explicit: "no"
podcast_author: Ethan Aubuchon, Bing Lin, and Will Damon
podcast_description: The Trail Busters podcast explores the realm of outdoor adventures. Three friends, Ethan, Bing and Will, share the good, the bad, and the goofy experiences of their outdoor adventures.
podcast_summary: The Trail Busters podcast explores the realm of outdoor adventures. Three friends, Ethan, Bing and Will, share the good, the bad, and the goofy experiences of their outdoor adventures.
podcast_subtitle: Talking Outdoors and Adventure

# Build settings
theme: minima
plugins:
  - audioinfo

collections:
  episodes:
    output: true

feed:
  collections:
    episodes:
      path: episodes.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
