title: The Trail Busters
email: info@thetrailbusters.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thetrailbusters.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thetrailbusters

# Podcast config
podcast_url: http://www.thetrailbusters.com
podcast_album_art: /img/trailbusters.jpg
podcast_title: The Trail Busters
podcast_owner: Ethan Aubuchon, Bing Lin, and Will Damon
podcast_email: contact@thetrailbusters.com
podcast_category: Sports
podcast_subcategory_one: Wilderness
podcast_explicit: "no"
podcast_author: Ethan Aubuchon, Bing Lin, and Will Damon
podcast_description: The Trail Busters podcast explores the realm of outdoor adventures. Three friends, Ethan, Bing and Will, share the good, the bad, and the goofy experiences of their outdoor adventures.
podcast_summary: The Trail Busters podcast explores the realm of outdoor adventures. Three friends, Ethan, Bing and Will, share the good, the bad, and the goofy experiences of their outdoor adventures.
podcast_subtitle: Talking Outdoors and Adventure

# Build settings
theme: minima
plugins:
  - audioinfo

collections:
  episodes:
    output: true

feed:
  collections:
    episodes:
      path: episodes.xml
    posts:
      path: posts.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
